const TodoActionTypes = {
  ADD_TODO_ITEM: 'ADD_TODO_ITEM',
  EDIT_TODO_ITEM: 'EDIT_TODO_ITEM',
  DELETE_TODO_ITEM: 'DELETE_TODO_ITEM',
  COMPLETE_TODO_ITEM: 'COMPLETE_TODO_ITEM',
  FIRE_INPUT_FIELD: 'FIRE_INPUT_FIELD',
  CLOSE_INPUT_FIELD: 'CLOSE_INPUT_FIELD',
  TICK_TODO_ITEM: 'TICK_TODO_ITEM',
}

export default TodoActionTypes;