const TodoActionTypes = {
  ADD_TODO_ITEM: 'ADD_TODO_ITEM',
  EDIT_TODO_ITEM: 'EDIT_TODO_ITEM',
  DELETE_TODO_ITEM: 'DELETE_TODO_ITEM',
  COMPLETE_TODO_ITEM: 'COMPLETE_TODO_ITEM',
  FIRE_INPUT_FIELD: 'FIRE_INPUT_FIELD',
  CLOSE_INPUT_FIELD: 'CLOSE_INPUT_FIELD',
  TICK_TODO_ITEM: 'TICK_TODO_ITEM',
  TRIGGER_EDIT_MODE: 'TRIGGER_EDIT_MODE',
  TRIGGER_VIEW_MODE: 'TRIGGER_VIEW_MODE'
}

export default TodoActionTypes;